ToDoProject:  
        # Schimba APP_NAME1 cu numele aplicatiei
        ToDoApp:
            - view_name: todo_list
              url_path_name: list
              template_name: todo_list
            - view_name: todo_details
              url_path_name: details
              template_name: todo_details
            - view_name: create_todo
              url_path_name: create
              template_name: create_todo
            - view_name: delete_todo
              url_path_name: delete
              template_name: delete_todo
            - view_name: update_todo
              url_path_name: update
              template_name: update_todo
              