# Generated by Django 5.1.6 on 2025-04-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPoest",
            new_name="BlogPost",
        ),
    ]
