# Generated by Django 5.1.6 on 2025-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blogpoest_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
